from __future__ import annotations

import csv
import io
from datetime import datetime
from typing import Iterable

from django.db.models import Avg, Count
from django.http import HttpResponse

from .analytics import department_rankings, faculty_rankings
from .models import Department, Evaluation, EvaluationAnswer, UserProfile

SUPPORTED_FORMATS = ("pdf", "excel", "csv", "word")


def build_report(report_type: str, fmt: str, **filters) -> HttpResponse:
    fmt = (fmt or "csv").lower()
    if fmt not in SUPPORTED_FORMATS:
        fmt = "csv"

    rows = _collect_rows(report_type, filters)
    headers = _headers_for(report_type)
    title = _title_for(report_type)

    if fmt == "csv":
        return _render_csv(title, headers, rows)
    if fmt == "excel":
        return _render_excel(title, headers, rows, fmt)
    if fmt == "word":
        return _render_word(title, headers, rows, fmt)
    return _render_pdf(title, headers, rows, fmt)

def _collect_rows(report_type: str, filters: dict) -> list[list]:
    if report_type == "evaluation_summary":
        return _evaluation_summary_rows(filters)
    if report_type == "faculty_ranking":
        return _faculty_ranking_rows(filters)
    return []


def _evaluation_summary_rows(filters: dict) -> list[list]:
    start, end = filters.get("start"), filters.get("end")
    qs = Evaluation.objects.all()
    if start:
        qs = qs.filter(created_at__gte=start)
    if end:
        qs = qs.filter(created_at__lte=end)

    rows: list[list] = []
    for dept in Department.objects.all():
        evaluations = qs.filter(department=dept)
        answers = EvaluationAnswer.objects.filter(evaluation__in=evaluations)
        agg = answers.aggregate(v=Avg("rating"), c=Count("id"))
        avg = agg["v"] or 0
        rows.append([
            dept.department_name,
            evaluations.count(),
            agg["c"] or 0,
            round(avg, 2),
            f"{round((avg / 5) * 100, 1)}%" if avg else "0%",
        ])
    return rows


def _faculty_ranking_rows(filters: dict) -> list[list]:
    department = filters.get("department")
    search = filters.get("search") or ""
    rows = faculty_rankings(department=department, search=search)
    return [[r["full_name"], r["department"],
             f"{r['percentage']}%", r["evaluations"], r["label"]]
            for r in rows]


def _headers_for(report_type: str) -> list[str]:
    if report_type == "evaluation_summary":
        return ["Grade Level", "Total Evaluations", "Total Answers",
                "Average Rating", "Satisfaction %"]
    if report_type == "faculty_ranking":
        return ["Faculty", "Grade Level", "Rating %", "Evaluations", "Band"]
    return []


def _title_for(report_type: str) -> str:
    return {
        "evaluation_summary": "FacuTrack – Evaluation Summary Report",
        "faculty_ranking":    "FacuTrack – Faculty Ranking Report",
    }.get(report_type, "FacuTrack – Report")

def _render_csv(title: str, headers: list[str], rows: Iterable[list]) -> HttpResponse:
    buffer = io.StringIO()
    writer = csv.writer(buffer)
    writer.writerow([title, datetime.now().strftime("%Y-%m-%d %H:%M")])
    writer.writerow([])
    writer.writerow(headers)
    for row in rows:
        writer.writerow(row)

    response = HttpResponse(buffer.getvalue(), content_type="text/csv")
    response["Content-Disposition"] = _disposition(title, "csv")
    return response


def _render_excel(title: str, headers: list[str], rows: Iterable[list], fmt: str) -> HttpResponse:
    try:
        from openpyxl import Workbook
    except ImportError:
        return _render_csv(title + " (install openpyxl for native Excel)", headers, rows)

    wb = Workbook()
    ws = wb.active
    ws.title = "Report"
    ws.append([title])
    ws.append([datetime.now().strftime("%Y-%m-%d %H:%M")])
    ws.append([])
    ws.append(headers)
    for row in rows:
        ws.append(row)

    buffer = io.BytesIO()
    wb.save(buffer)
    response = HttpResponse(
        buffer.getvalue(),
        content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    )
    response["Content-Disposition"] = _disposition(title, "xlsx")
    return response


def _render_word(title: str, headers: list[str], rows: Iterable[list], fmt: str) -> HttpResponse:
    try:
        from docx import Document
    except ImportError:
        return _render_csv(title + " (install python-docx for native Word)", headers, rows)

    doc = Document()
    doc.add_heading(title, level=1)
    doc.add_paragraph("Generated by FacuTrack · " + datetime.now().strftime("%Y-%m-%d %H:%M"))
    table = doc.add_table(rows=1, cols=len(headers))
    table.style = "Light Grid Accent 1"
    for i, h in enumerate(headers):
        table.rows[0].cells[i].text = h
    for row in rows:
        cells = table.add_row().cells
        for i, value in enumerate(row):
            cells[i].text = str(value)

    buffer = io.BytesIO()
    doc.save(buffer)
    response = HttpResponse(
        buffer.getvalue(),
        content_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    )
    response["Content-Disposition"] = _disposition(title, "docx")
    return response


def _render_pdf(title: str, headers: list[str], rows: Iterable[list], fmt: str) -> HttpResponse:
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.platypus import (
            Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
        )
    except ImportError:
        return _render_csv(title + " (install reportlab for native PDF)", headers, rows)

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, title=title)
    styles = getSampleStyleSheet()
    story = [
        Paragraph(title, styles["Title"]),
        Paragraph("Generated by FacuTrack · " + datetime.now().strftime("%Y-%m-%d %H:%M"),
                  styles["Normal"]),
        Spacer(1, 12),
    ]
    data = [headers] + [list(map(str, row)) for row in rows]
    if data:
        table = Table(data, repeatRows=1)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#d4af7f")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
        ]))
        story.append(table)
    doc.build(story)
    response = HttpResponse(buffer.getvalue(), content_type="application/pdf")
    response["Content-Disposition"] = _disposition(title, "pdf")
    return response


def _disposition(title: str, ext: str) -> str:
    safe = "".join(c if c.isalnum() or c in " -_" else "" for c in title).strip() or "facutrack-report"
    return f'attachment; filename="{safe}.{ext}"'
